baseURL = "https://coderbuck.github.io"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Buck's Bolg"
theme = "yinyang"


[params]
  headTitle = "Coder Buck"
  mainSections = ["posts"]

#  [[params.socials]]
#	name = "About Me"
#	link = "https://github.com/CoderBuck"
  

  [[params.socials]]
    name = "Github"
    link = "https://github.com/CoderBuck"

  [[params.socials]]
    name = "Twitter"
    link = "https://twitter.com/D20170806"

  postHeaderContent = ""
  postFooterContent = "<br/><br/><p>Subscribe toï¼š<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"
  # extraCSSFiles = ["css/foo.css", "css/bar.css"]
  extraCSSFiles = []
   
