baseURL = "https://coderbuck.github.io"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "Buck's Bolg"
theme = "yinyang"


[params]
  headTitle = "Coder Buck"
  mainSections = ["posts"]

#  [[params.socials]]
#	name = "About Me"
#	link = "https://github.com/CoderBuck"
  

  [[params.socials]]
    name = "Github"
    link = "https://github.com/CoderBuck"

  [[params.socials]]
    name = "Twitter"
    link = "https://twitter.com/D20170806"

#  [[params.socials]]
#    name = "About"
#    link = "/posts/about"  